"""
Django settings for notifications_system project.

Generated by 'django-admin startproject' using Django 3.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from .base import *

WSGI_APPLICATION = 'notifications_system.wsgi.application'
ASGI_APPLICATION = 'notifications_system.asgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# Database
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("POSTGRES_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("POSTGRES_DATABASE", ""),
        "USER": os.environ.get("POSTGRES_USER", ""),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("POSTGRES_PORT", 5432)
    }
}

REDIS_LOCATION = (f"redis://{os.environ.get('REDIS_HOST', '')}:"
                  f"{os.environ.get('REDIS_PORT', '')}/"
                  f"{os.environ.get('REDIS_DB', 0)}")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Use Redis as the channel layer backend
# Adjust the host and port as per your Redis configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(f"{os.environ.get('REDIS_HOST')}", f"{os.environ.get('REDIS_PORT', '')}")],
        },
    },
}

# Additional Sessions Config
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Redis configuration for Celery
CELERY_BROKER_URL = REDIS_LOCATION
