version: '3.9'

services:
  notifications_system:
    container_name: notifications_system
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    restart: always
    command: /start # /start-prod
    volumes:
      - ./notifications_system:/app
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    env_file:
      - .env
    depends_on:
      - db-citelink
      - redis
    networks:
      citelink-network:
    stdin_open: true
    tty: true

  db-citelink:
    container_name: citelink-database
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - postgresql_citelink:/var/lib/postgresql/data
    networks:
      citelink-network:

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/root/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    networks:
      citelink-network:

  celery:
    container_name: celery
    restart: always
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: /start-celeryworker
    volumes:
      - ./notifications_system:/app
    env_file:
      - .env
    depends_on:
      - db-citelink
      - redis
      - notifications_system
    networks:
      citelink-network:

  celery-beat:
    container_name: celery-beat
    restart: always
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: /start-celerybeat
    env_file:
      - .env
    volumes:
      - ./notifications_system:/app
    depends_on:
      - db-citelink
      - redis
      - notifications_system
      - celery
    networks:
      citelink-network:

volumes:
  notifications_system:
  postgresql_citelink:
  redis_data:
  redis.conf:

networks:
  citelink-network:
