version: '3.9'

services:
  test:
    container_name: pytest
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: pytest
    volumes:
      - ./notifications_system:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE_TEST}
    networks:
      citelink-network:
    stdin_open: true
    tty: true


networks:
  citelink-network:
