# Generated by Django 5.0.4 on 2024-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_persistent',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
