# Generated by Django 5.0.4 on 2024-08-13 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together={('user', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'notification')},
        ),
    ]
